import Navbar from '../components/layout/Navbar';
import Footer from '../components/layout/Footer';
import { Link } from '../components/routing/Link';

const sections = [
  { id: 'creation', title: 'Creation & Distribution', items: [
    'Creating deepfakes to impersonate someone without consent is illegal in many jurisdictions.',
    'Sharing or distributing fake images intended to defame, harass, or harm others may constitute defamation, harassment, or cyberbullying.',
    'Using deepfakes for fraud, extortion, or blackmail is a criminal offense.',
    'Generating non-consensual intimate imagery (e.g., revenge porn, "deepfake pornography") is illegal in numerous countries and may result in imprisonment.',
  ]},
  { id: 'copyright', title: 'Copyright & Intellectual Property', items: [
    'Using another person\'s likeness without permission may violate publicity rights or personality rights.',
    'Training AI models on copyrighted images without proper licensing can infringe copyright law.',
    'Publishing manipulated images that misrepresent original works may constitute copyright infringement or moral rights violations.',
  ]},
  { id: 'election', title: 'Election & Political Integrity', items: [
    'Many countries prohibit the use of deepfakes to influence elections or mislead voters.',
    'Publishing fabricated images of public figures with intent to spread misinformation may be subject to legal action.',
    'Regulations often require disclosure when media has been altered or generated by AI.',
  ]},
  { id: 'platform', title: 'Platform & Social Media', items: [
    'Most social media platforms prohibit the posting of misleading or deceptive content, including deepfakes.',
    'Users may face account suspension or legal liability for violating platform terms of service.',
    'Some jurisdictions mandate that platforms remove or label synthetic media.',
  ]},
  { id: 'reporting', title: 'Reporting & Liability', items: [
    'If you are harmed by a deepfake, you may have grounds for civil lawsuits (defamation, emotional distress, etc.).',
    'Report fake images used against you to the platform, law enforcement, and relevant authorities.',
    'Keep evidence: save URLs, screenshots, and metadata to support any legal or policy action.',
  ]},
];

export default function CyberRules() {
  return (
    <div className="min-h-screen flex flex-col bg-gray-50 dark:bg-gray-950">
      <Navbar />
      <main className="flex-1 w-full flex flex-col lg:flex-row">
        {/* Sidebar */}
        <aside className="lg:w-56 shrink-0 lg:sticky lg:top-20 lg:self-start order-2 lg:order-1 border-t lg:border-t-0 lg:border-r border-gray-200 dark:border-gray-800 bg-white dark:bg-gray-900 lg:bg-transparent lg:py-16">
          <div className="max-w-4xl lg:max-w-none mx-auto px-4 sm:px-6 lg:px-8 lg:pl-8 lg:pr-6 py-6 lg:py-0">
            <h3 className="text-xs font-semibold uppercase tracking-wider text-gray-500 dark:text-gray-400 mb-3">
              Sections
            </h3>
            <nav className="flex flex-wrap gap-2 lg:flex-col lg:gap-1">
              {sections.map((s) => (
                <a
                  key={s.id}
                  href={`#${s.id}`}
                  className="text-sm text-gray-600 dark:text-gray-400 hover:text-emerald-600 dark:hover:text-emerald-400 transition-colors lg:py-1"
                >
                  {s.title}
                </a>
              ))}
            </nav>
          </div>
        </aside>

        {/* Content */}
        <div className="flex-1 min-w-0 order-1 lg:order-2">
          <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 py-12 lg:py-16">
            <header className="mb-12">
              <h1 className="text-3xl sm:text-4xl font-bold text-gray-900 dark:text-white mb-3">
                Cyber Rules & Laws on Fake Images
              </h1>
              <p className="text-lg text-gray-600 dark:text-gray-400 leading-relaxed">
                Legal and regulatory frameworks governing the creation, use, and distribution of deepfakes and manipulated images.
              </p>
            </header>

            <div className="space-y-8">
              {sections.map((section) => (
                <section
                  key={section.id}
                  id={section.id}
                  className="scroll-mt-24 rounded-xl border border-gray-200 dark:border-gray-800 bg-white dark:bg-gray-900 overflow-hidden"
                >
                  <div className="px-5 py-4 border-b border-gray-200 dark:border-gray-800 bg-gray-50 dark:bg-gray-800/50">
                    <h2 className="text-lg font-semibold text-gray-900 dark:text-white">
                      {section.title}
                    </h2>
                  </div>
                  <div className="px-5 py-4 space-y-3">
                    {section.items.map((item, j) => (
                      <p
                        key={j}
                        className="pl-4 border-l-2 border-emerald-500/40 text-gray-600 dark:text-gray-400 text-sm leading-relaxed"
                      >
                        {item}
                      </p>
                    ))}
                  </div>
                </section>
              ))}
            </div>

            <div className="mt-10 p-4 rounded-xl bg-amber-50 dark:bg-amber-900/20 border border-amber-200 dark:border-amber-800/50">
              <p className="text-sm text-amber-800 dark:text-amber-200">
                <strong>Disclaimer:</strong> Laws vary by country and region. This is general guidance, not legal advice. Consult a lawyer for your specific situation.
              </p>
            </div>

            <div className="mt-14 pt-8 border-t border-gray-200 dark:border-gray-800 flex flex-wrap gap-3 justify-center">
              <Link href="/" className="inline-flex items-center gap-2 px-4 py-2.5 rounded-lg bg-gray-200 dark:bg-gray-800 text-gray-800 dark:text-gray-200 text-sm font-medium hover:bg-gray-300 dark:hover:bg-gray-700 transition-colors">
                ← Home
              </Link>
              <Link href="/help" className="inline-flex items-center gap-2 px-4 py-2.5 rounded-lg bg-emerald-600 dark:bg-emerald-500 text-white text-sm font-medium hover:bg-emerald-700 dark:hover:bg-emerald-600 transition-colors">
                Help Guide →
              </Link>
            </div>
          </div>
        </div>
      </main>
      <Footer />
    </div>
  );
}
